---
version: "3"
services:
  simsim:
    build: .
    image: simsim:latest
    container_name: simsim
    environment:
      - TZ=America/Detroit
    # volumes:
    #   - <path to config>:/config
    restart: unless-stopped
    labels:
      - traefik.http.routers.simsim.rule=Host(`simsim.minibook.io`)
      - traefik.http.routers.simsim.tls=true
      - traefik.http.routers.simsim.tls.certresolver=lets-encrypt
      - traefik.port=8008
    networks:
      - web

networks:
  web:
    external: true
